wandb_key=$1
dataset=$2
model=$3
model_name=$4
n_examples=$5
seed=$6 

WANDB_API_KEY=$wandb_key accelerate launch --config_file accelerate_config/fsdp_8gpu.yaml --main_process_port 29500 launch.py \
    n_examples=$n_examples \
    loss=sft \
    model=$model \
    datasets=[$dataset] \
    exp_name=sft/seed_$seed \
    seed=$seed \
    ++cache_dir=.cache/data/$dataset/$model_name/ \
    ++model.name_or_path=$model_name \
    ++lr=5e-6 \
    ++loss.beta=0.1 \
    model.batch_size=32 \
    model.eval_batch_size=32 \
    model.max_length=512 \
    model.max_prompt_length=256
